baseURL = "https://example.com"
title = "Origin"
author = "Christopher Gandrud"
copyright = "Â© 2020, Christopher Gandrud"
paginate = 4
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin"

[params]
  description = "simple hugo theme"
  featured = true
  cssonly = false

  [params.socials]
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

